### ISSUE TITLE
卒業制作[4] issueベースの開発

### ISSUE THREAD

**Issue by mtk177a** [mtk177a/lockaway#5]
### 実装予定の機能

- [ ] ユーザー登録機能
- [ ] ログイン機能
- [ ] ログアウト機能
- [ ] 習慣登録機能
- [ ] 習慣一覧表示機能
- [ ] 習慣編集機能
- [ ] 習慣削除機能
- [ ] 習慣達成状況のログ記録機能
- [ ] いいね機能
- [ ] コメント機能
- [ ] フォロー機能
- [ ] 習慣記録リマインド機能
- [ ] 報酬機能

### 必要なページ

- [ ] トップページ
- [ ] 全ユーザーの習慣一覧画面
- [ ] 全ユーザーの報酬（リワード）一覧画面
- [ ] ユーザー新規登録画面
- [ ] ログイン画面
- [ ] ダッシュボード画面・ログインしているユーザーの習慣一覧
- [ ] ダッシュボード画面・ログインしているユーザーの報酬（リワード）一覧
- [ ] プロフィール画面
- [ ] ログイン前共通ヘッダー
- [ ] ログイン後共通ヘッダー
- [ ] フォローしているユーザー一覧画面
- [ ] フォロワー一覧画面
- [ ] ユーザー一覧
- [ ] 習慣登録画面
- [ ] 習慣編集画面
- [ ] 習慣詳細画面
- [ ] 共通フッター
- [ ] 利用規約画面
- [ ] プライバシーポリシー画面
- [ ] お問い合わせ画面

**Comment by Tsuchiya2** [comment]
ご提出ありがとうございます。
以下コメントになります。

---

ややストーリーポイント5のものが多い印象を受けました。おそらく初めて取り組むものや画面の作成といったものが含まれるため5ポイントとしているかと推測しました。それらに関してですが、ストーリーポイント1,2になるまで細分化すると、どこまでは見通しが立っていて、どの辺りが可視化されていないかが明確化するので実践しましょう。また、ストーリーポイントを小さくすることで、進捗を感じられながら開発を進めることができます。

**Comment by tmtkzk0823** [comment]
修正ありがとうございます。
概ね良さそうです。
LGTMです！
