### ISSUE TITLE
MVPリリース

### ISSUE THREAD

**Issue by mtk177a** [mtk177a/lockaway#77]
### サービス名

LockAway

### サービスURL

https://lockaway-fbeb557015fd.herokuapp.com/

## READMEレビュー時にMVPリリース時点で実装予定だった機能

- [x] ユーザー登録・認証
  - [x] ユーザー登録
  - [x] ログイン
  - [x] ログアウト
- [x] 習慣の管理機能
  - [x] 一覧
  - [x] 表示
  - [x] 登録
  - [x] 編集
  - [x] 削除
- [x] 達成状況の表示機能（習慣ログ）
  - [x] 一覧
  - [x] 表示
- [x] 報酬機能
  - [x] 獲得報酬一覧
- [ ] ソーシャル機能
  - [ ] いいね
  - [ ] フォロー
  - [ ] 通知機能
  - [x] 習慣記録時間や特定のイベントに対してユーザーに通知を提供（未記録の習慣ログがある場合のメッセージ表示）

## READMEレビュー時から変更した機能

下記の機能をMVPリリースから外し、本リリース時に実装する機能・画面としました。
5/16の卒業認定までの開発スケジュール見積もり面談にて、とみた講師に確認いただいています。

- [ ] トップページ
- [ ] 利用規約
- [ ] プライバシーポリシー
- [ ] いいね機能
- [ ] コメント機能
- [ ] フォロー機能

### 一般ユーザー画面

| ユーザーの習慣一覧 | 習慣詳細 |
| --- | --- |
| [![Image from Gyazo](https://i.gyazo.com/0da6d9e6281bce0060cf7bc8544208c7.png)](https://gyazo.com/0da6d9e6281bce0060cf7bc8544208c7) | [![Image from Gyazo](https://i.gyazo.com/453e2589eb5589b8c888f2d284b56035.png)](https://gyazo.com/453e2589eb5589b8c888f2d284b56035) |

| 新規習慣作成 | 習慣編集 |
| --- | --- |
| [![Image from Gyazo](https://i.gyazo.com/83124b06577443a5bdf2955669a1c0ce.png)](https://gyazo.com/83124b06577443a5bdf2955669a1c0ce) | [![Image from Gyazo](https://i.gyazo.com/31922502307f1f483cc8d64abfbe92cd.png)](https://gyazo.com/31922502307f1f483cc8d64abfbe92cd) |

| 未記録の習慣ログ一覧 | ユーザーの獲得した報酬一覧 |
| --- | --- |
| [![Image from Gyazo](https://i.gyazo.com/d5faa05a8ae6d1fcea691f9f2eb92d19.png)](https://gyazo.com/d5faa05a8ae6d1fcea691f9f2eb92d19) | [![Image from Gyazo](https://i.gyazo.com/3b4a7d26dbcdaf61b367c30b726e528f.png)](https://gyazo.com/3b4a7d26dbcdaf61b367c30b726e528f) |

| みんなの習慣一覧 | みんなの獲得報酬一覧 |
| --- | --- |
| [![Image from Gyazo](https://i.gyazo.com/4852ed3cc61f7ac9326f7a3f9c9c2c26.png)](https://gyazo.com/4852ed3cc61f7ac9326f7a3f9c9c2c26) | [![Image from Gyazo](https://i.gyazo.com/0c2becd4ded49c65cce63e279c6e8f03.png)](https://gyazo.com/0c2becd4ded49c65cce63e279c6e8f03) |

### 管理者ユーザー画面

| ダッシュボード画面 | 報酬管理画面 |
| --- | --- |
| [![Image from Gyazo](https://i.gyazo.com/ca2113419f006391242d92687a0fdfc4.png)](https://gyazo.com/ca2113419f006391242d92687a0fdfc4) | [![Image from Gyazo](https://i.gyazo.com/28cb3ab2e32689a38df18a05f6f28d45.png)](https://gyazo.com/28cb3ab2e32689a38df18a05f6f28d45) |

| ユーザー管理画面 | 習慣管理画面 |
| --- | --- |
| [![Image from Gyazo](https://i.gyazo.com/4c639e3f24b90b121dd92799a5ca942f.png)](https://gyazo.com/4c639e3f24b90b121dd92799a5ca942f) | [![Image from Gyazo](https://i.gyazo.com/23797fefe699b23910d447f72e156c76.png)](https://gyazo.com/23797fefe699b23910d447f72e156c76) |

**Comment by Tsuchiya2** [comment]
機能確認が取れました。LGTMです！
引き続き本リリースに向けて開発頑張ってください。
